server:
  port: 8000
spring:
  application:
    name: server-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: test
        import-check:
          enabled: false



---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: dev

#---
#spring:
#  config:
#    import:
#      - nacos:common.properties?group=order
#      - nacos:database.properties?group=order
#    activate:
#      on-profile: test
#
#
#---
#spring:
#  config:
#    import:
#      - nacos:common.properties?group=order
#      - nacos:database.properties?group=order
#    activate:
#      on-profile: prod